#include "main.h"

class_info class_data[] = {{"Monster", "Монстр", 8, Strenght, {Monster},
{BonusHits}, {0, 0, 0, 0, 0, 0},
{Human, Dwarf, Elf, Gnome, HalfElf, Humanoid, Animal, Insectoid}},
{"Cleric", "Священник", 8, Wisdow, {Cleric},
{NoExeptionalStrenght, UseLeatherArmor, UseMetalArmor, UseShield}, {0, 0, 0, 0, 9, 0},
{Human, Dwarf, Elf, Gnome, HalfElf, Humanoid}},
{"Fighter", "Боец", 10, Strenght, {Fighter},
{UseLeatherArmor, UseMetalArmor, UseShield, BonusHits}, {9, 0, 7, 0, 0, 0},
{Human, Dwarf, Elf, Gnome, HalfElf, Halfling, Humanoid}},
{"Mage", "Маг", 4, Intellegence, {Mage},
{NoExeptionalStrenght}, {0, 6, 0, 9, 0, 0},
{Human, Elf, HalfElf, Humanoid}},
{"Paladin", "Паладин", 10, Strenght, {Paladin},
{HolyGrace, UseLeatherArmor, UseMetalArmor, UseShield}, {12, 0, 9, 13, 0, 17},
{Human}},
{"Ranger", "Следопыт", 8, Strenght, {Ranger},
{UseLeatherArmor, UseMetalArmor, UseShield}, {13, 0, 14, 13, 14, 0},
{Human}, 1},
{"Theif", "Вор", 6, Dexterity, {Theif},
{NoExeptionalStrenght, UseLeatherArmor}, {0, 9, 0, 0, 0, 0},
{Human, Dwarf, Elf, Gnome, HalfElf, Halfling, Humanoid}},
//
{"FighterCleric", "Воин-священник", 0, Strenght, {Fighter, Cleric},
{UseLeatherArmor, UseMetalArmor, UseShield, BonusHits}, {9, 0, 7, 0, 15, 0},
{HalfElf}},
{"FighterMage", "Воин-маг", 0, Strenght, {Fighter, Mage},
{UseLeatherArmor, UseShield, BonusHits}, {9, 0, 7, 9, 0, 0},
{Elf, HalfElf}},
{"FighterTheif", "Воин-вор", 0, Strenght, {Fighter, Theif},
{UseLeatherArmor, UseShield, BonusHits}, {9, 9, 7, 0, 0, 0},
{Dwarf, Elf, Gnome, HalfElf, Halfling}},
{"ClericMage", "Священник-маг", 0, Wisdow, {Cleric, Mage},
{NoExeptionalStrenght, UseShield}, {0, 0, 0, 9, 15, 0},
{HalfElf}},
{"MageTheif", "Маг-вор", 0, Intellegence, {Mage, Theif},
{NoExeptionalStrenght}, {0, 9, 0, 9, 0, 0},
{Elf, HalfElf}},
{"FighterClericMage", "Воин-священник-маг", 0, Strenght, {Fighter, Cleric, Mage},
{UseLeatherArmor, UseShield, BonusHits}, {9, 0, 7, 9, 15, 0},
{HalfElf}},
{"FighterMageTheif", "Воин-маг-вор", 0, Strenght, {Fighter, Mage, Theif},
{UseLeatherArmor, UseShield, BonusHits}, {9, 9, 7, 9, 0, 0},
{Elf, HalfElf}},
};
assert_enum(class, FighterMageTheif);
getstr_enum(class);