#include "main.h"

class_info bsmeta<class_info>::elements[] = {{"Monster", "Монстр", 0, 8, Strenght, {Monster},
{BonusHits}, {}, {0, 0, 0, 0, 0, 0},
{Human, Dwarf, Elf, Gnome, HalfElf, Goblinoid, Humanoid, Animal, Insectoid}},
{"Cleric", "Священник", 1, 8, Wisdow, {Cleric},
{NoExeptionalStrenght}, {UseLeatherArmor, UseMetalArmor, UseShield}, {0, 0, 0, 0, 9, 0},
{Human, Dwarf, Elf, Gnome, HalfElf, Goblinoid, Humanoid}},
{"Fighter", "Боец", 1, 10, Strenght, {Fighter},
{BonusHits}, {UseLeatherArmor, UseMetalArmor, UseShield, UseTheifWeapon, UseMartialWeapon}, {9, 0, 7, 0, 0, 0},
{Human, Dwarf, Elf, Gnome, HalfElf, Halfling, Goblinoid, Humanoid}},
{"Mage", "Маг", 1, 4, Intellegence, {Mage},
{NoExeptionalStrenght}, {}, {0, 6, 0, 9, 0, 0},
{Human, Elf, HalfElf, Goblinoid, Humanoid}},
{"Paladin", "Паладин", 1, 10, Strenght, {Paladin},
{HolyGrace}, {UseLeatherArmor, UseMetalArmor, UseShield, UseTheifWeapon, UseMartialWeapon}, {12, 0, 9, 13, 0, 17},
{Human}},
{"Ranger", "Следопыт", 1, 8, Strenght, {Ranger},
{}, {UseLeatherArmor, UseMetalArmor, UseShield, UseTheifWeapon, UseMartialWeapon}, {13, 0, 14, 13, 14, 0},
{Human}, 1},
{"Theif", "Вор", 1, 6, Dexterity, {Theif},
{NoExeptionalStrenght}, {UseLeatherArmor, UseTheifWeapon}, {0, 9, 0, 0, 0, 0},
{Human, Dwarf, Elf, Gnome, HalfElf, Halfling, Goblinoid, Humanoid}},
//
{"FighterCleric", "Воин-священник", 1, 0, Strenght, {Fighter, Cleric},
{BonusHits}, {UseLeatherArmor, UseMetalArmor, UseShield, UseTheifWeapon, UseMartialWeapon}, {9, 0, 7, 0, 15, 0},
{HalfElf, Goblinoid}},
{"FighterMage", "Воин-маг", 1, 0, Strenght, {Fighter, Mage},
{BonusHits}, {UseLeatherArmor, UseShield, UseTheifWeapon, UseMartialWeapon}, {9, 0, 7, 9, 0, 0},
{Elf, HalfElf, Goblinoid}},
{"FighterTheif", "Воин-вор", 1, 0, Strenght, {Fighter, Theif},
{BonusHits}, {UseLeatherArmor, UseShield, UseTheifWeapon, UseMartialWeapon}, {9, 9, 7, 0, 0, 0},
{Dwarf, Elf, Gnome, HalfElf, Halfling, Goblinoid}},
{"ClericMage", "Священник-маг", 1, 0, Wisdow, {Cleric, Mage},
{NoExeptionalStrenght}, {UseShield}, {0, 0, 0, 9, 15, 0},
{HalfElf}},
{"MageTheif", "Маг-вор", 1, 0, Intellegence, {Mage, Theif},
{NoExeptionalStrenght}, {UseTheifWeapon}, {0, 9, 0, 9, 0, 0},
{Elf, HalfElf, Goblinoid}},
{"FighterClericMage", "Воин-священник-маг", 1, 0, Strenght, {Fighter, Cleric, Mage},
{BonusHits}, {UseLeatherArmor, UseShield, UseTheifWeapon, UseMartialWeapon}, {9, 0, 7, 9, 15, 0},
{HalfElf}},
{"FighterMageTheif", "Воин-маг-вор", 1, 0, Strenght, {Fighter, Mage, Theif},
{BonusHits}, {UseLeatherArmor, UseShield, UseTheifWeapon, UseMartialWeapon}, {9, 9, 7, 9, 0, 0},
{Elf, HalfElf}},
};
assert_enum(class, FighterMageTheif);